site_name: "Projeto Sistemas Abertos"
site_description: "Linux, Redes e Arquitetura de Sistemas"
site_author: "Edenilson Freitas"

theme:
  name: material
  palette:
    scheme: slate
    primary: blue
    accent: cyan
  font:
    text: Roboto
    code: Fira Code

extra_css:
  - stylesheets/extra.css

nav:
  - Início: index.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true    